server:
  port: 8080

spring:
  application:
    name: demo

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
#    username: ${DB_USERNAME:user}
#    password: ${DB_PASSWORD:password}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    consumer:
#      group-id: ${KAFKA_CONSUMER_GROUP_ID:${spring.application.name}-group}
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.springframework.kafka: info
#    org.apache.kafka: warn
